#!/usr/bin/env python3
"""Script to list all databases in MongoDB."""

from pymongo import MongoClient

def list_databases():
    """Prints a list of all databases on the server."""
    client = MongoClient("mongodb://localhost:27017/")
    databases = client.list_database_names()
    for db in databases:
        print(db)

if __name__ == "__main__":
    list_databases()
